server:
  port: 8068
spring:
  application:
    name: holyWar
  main:
    allow-bean-definition-overriding: true
  #解决restful 404错误 spring.mvc.throw-exception-if-no-handler-found=true spring.resources.add-mappings=false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  #    profiles:
  #        active: dev
  servlet:
    multipart:
      max-file-size: 900MB
      max-request-size: 1000MB
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.106.78.98:3307/crusade?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      max-active: 20
      initial-size: 5
      max-wait: -1
      min-idle: 1
      filters: stat,wall,slf4j
# 访问地址：http://localhost:8068/doc.html
swagger2:
  enable: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
football:
  url: https://www.zgzcw.com/
logging:
  level:
    com.bright.dao: DEBUG